/**
 * Emits src/sim/trig.table.ts: sin for 0..90 degrees in 0.1 degree steps (901 entries).
 * Math.sin is allowed HERE (a build script) and banned in src/sim. The table is committed,
 * so every engine reads identical literals.
 */
const lines: string[] = [];
lines.push('// GENERATED by scripts/gen-trig.ts. Do not edit. Regenerate with `npm run gen:trig`.');
lines.push(
  '// sin(deciDeg / 10 degrees) for deciDeg in 0..900. Float64 literals, round-trip exact.',
);
lines.push('export const SIN_TABLE: readonly number[] = [');
for (let d = 0; d <= 900; d++) {
  const v = Math.sin((d / 10) * (Math.PI / 180));
  lines.push(`  ${v === 0 ? '0' : v.toString()},`);
}
lines.push('];');
process.stdout.write(lines.join('\n') + '\n');
